chore: Make release validation robust to transient failures (#214)

diff --git a/codebuild/release/validate.yml b/codebuild/release/validate.yml
--- a/codebuild/release/validate.yml
+++ b/codebuild/release/validate.yml
@@ -18,4 +18,20 @@ phases:
       - cd api_compatibility_tests
   build:
     commands:
-      - tox -e py38-awses_cli_${VERSION}
+      - NUM_RETRIES=3
+      - |
+        while [ $NUM_RETRIES -gt 0 ]
+        do
+          tox -e py38-awses_cli_${VERSION}
+          if [ $? -eq 0 ]; then
+            break
+          fi
+          NUM_RETRIES=$((NUM_RETRIES-1))
+          if [ $NUM_RETRIES -eq 0 ]; then
+            echo "All validation attempts failed, stopping"
+            exit 1;
+          else
+            echo "Validation failed, retrying in 60 seconds; will retry $NUM_RETRIES more times" && sleep 60
+          fi
+        done
+
